POST http://localhost:3000/auth/login
Content-Type: application/json

{ 
    "username": "phucthaii1820",
    "password": "123" 
}

###

GET http://localhost:3000/auth/test
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Ijp7Il9pZCI6IjYyODc2OWM0ZTVmOWQwN2EzNDgyY2FmZiIsInVzZXJuYW1lIjoicGh1Y3RoYWlpMTgyMCIsInBhc3N3b3JkIjoiJGFyZ29uMmkkdj0xOSRtPTQwOTYsdD0zLHA9MSRXWjlVaVUwS0dlMld6cHZYVkdYeDhRJDlIVzJMaU90WTc0TFNNQU91SWhKa3V6ZjdCVDRXTCtjbFFDSWsyMDIwUnMiLCJyb2xlIjoxfSwiaWF0IjoxNjUzMTU3NTA4LCJleHAiOjE2NTMzMzAzMDh9.XBoXnNAWY8O5SYklEOjW4XsM8L1Jym3Oqf02aoRYq0w


###
POST https://fit-summer-2022-ec-ommerce.vercel.app/auth/login
Content-Type: application/json

{ 
    "username": "phucthaii1820",
    "password": "123" 
}